# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Natan Felles
email: natanfelles@gmail.com
description: Às vezes eu programo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://natanfelles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: natanfelles
github_username:  natanfelles

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock

# Outputting
permalink: none
paginate: 5
paginate_path: /page-:num

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Natan Felles"

disqus:
  shortname: natanfelles

google_analytics: UA-75463090-1

author:
  name: Natan Felles
  twitter_username: natanfelles
  #facebook_username: natanfelles
  #linkedin_username: natanfelles
  github_username: natanfelles
  email: natanfelles@gmail.com

branch: master
