title: Natan Felles
email: natanfelles@gmail.com
description: Às vezes eu programo.
baseurl: ""
url: "https://natanfelles.github.io"
twitter_username: natanfelles
github_username:  natanfelles

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock

permalink: none
paginate: 5
paginate_path: /page-:num

defaults:
  -
    values:
      author: "Natan Felles"
      image: /assets/img/social.png
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      image: /assets/img_posts/post.png

disqus:
  shortname: natanfelles

google_analytics: UA-75463090-1
google_site_verification: 7YAsvH47ykUFB4n7rYiqT6A9mi0WF5y_DjzRtUco4IY

author:
  name: Natan Felles
  twitter_username: natanfelles
  #facebook_username: natanfelles
  #linkedin_username: natanfelles
  github_username: natanfelles
  email: natanfelles@gmail.com

branch: master
