title: Natan Felles
email: natanfelles@gmail.com
description: Creative Webmaster
baseurl: ""
url: "https://natanfelles.github.io"

timezone: America/Sao_Paulo

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /blog/:title
paginate: 5
paginate_path: /blog/:num

defaults:
  -
    values:
      author: "Natan Felles"
      image: /assets/img/social.png
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      image: /assets/img_posts/post.png

disqus_shortname: natanfelles

google_analytics: UA-75463090-1
google_site_verification: 7YAsvH47ykUFB4n7rYiqT6A9mi0WF5y_DjzRtUco4IY

author:
  name: Natan Felles
  twitter_username: natanfelles
  #facebook_username: natanfelles
  #linkedin_username: natanfelles
  github_username: natanfelles
  email: natanfelles@gmail.com
  twitter: natanfelles

branch: master

facebook:
  app_id: 1744716995840585
  publisher: 1007807062628320

twitter:
  username: natanfelles

logo: /assets/img/logo.png
